
import { Destination, Festival } from './types';

export const CONTACT_PHONE = "+9779846812395";

export const POPULAR_DESTINATIONS: Destination[] = [
  {
    id: 'mardi-himal',
    name: 'Mardi Himal',
    category: 'trekking',
    region: 'Kaski',
    province: 'Gandaki',
    description: 'The most affordable short trek. Perfect for anyone looking for high mountain views without a high price tag.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    difficulty: 'Easy',
    altitude: '4,500m',
    bestTime: 'Sep-Dec',
    mediums: ['Jeep', 'Trek'],
    priceRange: 'From $150',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'poon-hill',
    name: 'Poon Hill',
    category: 'trekking',
    region: 'Ghorepani',
    province: 'Gandaki',
    description: 'A classic budget trek. Very accessible with local transport and low-cost community lodges.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    difficulty: 'Easy',
    altitude: '3,210m',
    bestTime: 'Mar-May, Oct-Dec',
    mediums: ['Bus', 'Trek'],
    priceRange: 'From $120',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'ktm-durbar-square',
    name: 'Kathmandu Durbar Square',
    category: 'heritage',
    region: 'Kathmandu',
    province: 'Bagmati',
    description: 'Historic heart of the city. Entry is only a few dollars for a full day of culture.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'Entry $8',
    budgetLevel: 'Budget',
    rating: 4.7
  },
  {
    id: 'pashupatinath',
    name: 'Pashupatinath Temple',
    category: 'pilgrimage',
    region: 'Kathmandu',
    province: 'Bagmati',
    description: 'A sacred spiritual site. Accessible to all with minimal entry costs for visitors.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'Entry $7',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'lumbini-peace',
    name: 'Lumbini (Peace Garden)',
    category: 'pilgrimage',
    region: 'Rupandehi',
    province: 'Lumbini',
    description: 'The birthplace of Buddha. You can stay in monasteries for very low donations.',
    imageUrl: 'https://images.unsplash.com/photo-1623062633718-d78b27346123?q=80&w=1000',
    bestTime: 'Oct-Mar',
    mediums: ['Bus'],
    priceRange: 'From $15/day',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'pokhara-lakeside',
    name: 'Pokhara Lakeside',
    category: 'nature',
    region: 'Kaski',
    province: 'Gandaki',
    description: 'Beautiful lakes and mountain views. Budget hostels are available everywhere for $5-$10.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'Sep-Jun',
    mediums: ['Bus'],
    priceRange: 'From $10/day',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'nagarkot',
    name: 'Nagarkot Hill Station',
    category: 'nature',
    region: 'Bhaktapur',
    province: 'Bagmati',
    description: 'Famous for sunrise views. Easily reachable by local bus for a low-cost getaway.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    bestTime: 'Oct-Mar',
    mediums: ['Bus'],
    priceRange: 'From $20',
    budgetLevel: 'Budget',
    rating: 4.6
  },
  {
    id: 'ebc-trek',
    name: 'Everest Base Camp',
    category: 'trekking',
    region: 'Solukhumbu',
    province: 'Koshi',
    description: 'The ultimate trekking destination. Follow the footsteps of legends to the base of the world\'s highest peak.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    difficulty: 'Hard',
    altitude: '5,364m',
    bestTime: 'Mar-May, Oct-Dec',
    mediums: ['Flight', 'Trek'],
    priceRange: 'From $1,200',
    budgetLevel: 'Premium',
    rating: 5.0
  },
  {
    id: 'abc-trek',
    name: 'Annapurna Base Camp',
    category: 'trekking',
    region: 'Kaski',
    province: 'Gandaki',
    description: 'A breathtaking amphitheater of mountains. Experience diverse landscapes and rich Gurung culture.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    difficulty: 'Moderate',
    altitude: '4,130m',
    bestTime: 'Mar-May, Oct-Dec',
    mediums: ['Bus', 'Jeep', 'Trek'],
    priceRange: 'From $500',
    budgetLevel: 'Mid-range',
    rating: 4.9
  },
  {
    id: 'chitwan-national-park',
    name: 'Chitwan National Park',
    category: 'wildlife',
    region: 'Chitwan',
    province: 'Bagmati',
    description: 'A UNESCO World Heritage site known for one-horned rhinos, tigers, and elephant safaris.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    bestTime: 'Oct-Mar',
    mediums: ['Bus', 'Flight'],
    priceRange: 'From $60/day',
    budgetLevel: 'Mid-range',
    rating: 4.8
  },
  {
    id: 'bardia-national-park',
    name: 'Bardia National Park',
    category: 'wildlife',
    region: 'Bardiya',
    province: 'Lumbini',
    description: 'The largest and most undisturbed national park in Nepal\'s Terai. Best chance to spot a wild tiger.',
    imageUrl: 'https://images.unsplash.com/photo-1623062633718-d78b27346123?q=80&w=1000',
    bestTime: 'Nov-Apr',
    mediums: ['Bus', 'Flight'],
    priceRange: 'From $80/day',
    budgetLevel: 'Mid-range',
    rating: 4.9
  },
  {
    id: 'janakpur-temple',
    name: 'Janaki Mandir',
    category: 'pilgrimage',
    region: 'Dhanusha',
    province: 'Madhesh',
    description: 'Stunning Mughal-Hindu style architecture. The birthplace of Goddess Sita.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    bestTime: 'Oct-Mar',
    mediums: ['Bus', 'Flight'],
    priceRange: 'From $20/day',
    budgetLevel: 'Budget',
    rating: 4.7
  },
  {
    id: 'bandipur-village',
    name: 'Bandipur',
    category: 'hill-station',
    region: 'Tanahun',
    province: 'Gandaki',
    description: 'A living museum of Newari culture. Preserved ancient buildings and incredible mountain views.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'Oct-May',
    mediums: ['Bus'],
    priceRange: 'From $30/day',
    budgetLevel: 'Mid-range',
    rating: 4.8
  },
  {
    id: 'upper-mustang',
    name: 'Upper Mustang',
    category: 'trekking',
    region: 'Mustang',
    province: 'Gandaki',
    description: 'The "Forbidden Kingdom". High-altitude desert, ancient caves, and unique Tibetan culture.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    difficulty: 'Hard',
    altitude: '3,840m',
    bestTime: 'May-Oct (Rain Shadow)',
    mediums: ['Flight', 'Jeep', 'Trek'],
    priceRange: 'From $1,500',
    budgetLevel: 'Premium',
    rating: 4.9
  },
  {
    id: 'rara-lake',
    name: 'Rara Lake',
    category: 'nature',
    region: 'Mugu',
    province: 'Karnali',
    description: 'Nepal\'s largest and deepest freshwater lake. A hidden gem of pristine wilderness.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    altitude: '2,990m',
    bestTime: 'Apr-Jun, Sep-Oct',
    mediums: ['Flight', 'Trek', 'Jeep'],
    priceRange: 'From $400',
    budgetLevel: 'Mid-range',
    rating: 4.9
  },
  {
    id: 'gosaikunda-lake',
    name: 'Gosaikunda Lake',
    category: 'pilgrimage',
    region: 'Rasuwa',
    province: 'Bagmati',
    description: 'Sacred alpine lake. A major pilgrimage site for Hindus during Janai Purnima.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    difficulty: 'Moderate',
    altitude: '4,380m',
    bestTime: 'Mar-May, Sep-Nov',
    mediums: ['Bus', 'Trek'],
    priceRange: 'From $200',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'bhaktapur-square',
    name: 'Bhaktapur Durbar Square',
    category: 'heritage',
    region: 'Bhaktapur',
    province: 'Bagmati',
    description: 'The "City of Devotees". Known for its pottery, woodcarving, and medieval vibe.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'Entry $15',
    budgetLevel: 'Mid-range',
    rating: 4.9
  },
  {
    id: 'patan-square',
    name: 'Patan Durbar Square',
    category: 'heritage',
    region: 'Lalitpur',
    province: 'Bagmati',
    description: 'The city of fine arts. Explore the Golden Temple and the amazing Patan Museum.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'Entry $10',
    budgetLevel: 'Mid-range',
    rating: 4.8
  },
  {
    id: 'muktinath-temple',
    name: 'Muktinath Temple',
    category: 'pilgrimage',
    region: 'Mustang',
    province: 'Gandaki',
    description: 'Sacred to both Hindus and Buddhists. Features 108 water sprouts and eternal flames.',
    imageUrl: 'https://images.unsplash.com/photo-1623062633718-d78b27346123?q=80&w=1000',
    altitude: '3,710m',
    bestTime: 'Mar-Jun, Sep-Dec',
    mediums: ['Flight', 'Jeep', 'Trek'],
    priceRange: 'From $300',
    budgetLevel: 'Mid-range',
    rating: 4.9
  },
  {
    id: 'tilicho-lake',
    name: 'Tilicho Lake',
    category: 'trekking',
    region: 'Manang',
    province: 'Gandaki',
    description: 'One of the highest lakes in the world. Part of the Annapurna Circuit with dramatic glacial views.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    difficulty: 'Hard',
    altitude: '4,919m',
    bestTime: 'Mar-May, Oct-Dec',
    mediums: ['Jeep', 'Trek'],
    priceRange: 'From $400',
    budgetLevel: 'Mid-range',
    rating: 4.9
  },
  {
    id: 'shey-phoksundo',
    name: 'Shey Phoksundo Lake',
    category: 'nature',
    region: 'Dolpa',
    province: 'Karnali',
    description: 'Stunning deep blue lake in Upper Dolpa. Surreal scenery with zero pollution.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    altitude: '3,611m',
    bestTime: 'Apr-Oct',
    mediums: ['Flight', 'Trek'],
    priceRange: 'From $800',
    budgetLevel: 'Premium',
    rating: 5.0
  },
  {
    id: 'tansen-palpa',
    name: 'Tansen (Palpa)',
    category: 'hill-station',
    region: 'Palpa',
    province: 'Lumbini',
    description: 'Ancient hill town known for its Dhaka fabric and the "Taj Mahal of Nepal" - Rani Mahal.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'From $20/day',
    budgetLevel: 'Budget',
    rating: 4.7
  },
  {
    id: 'ilam-tea',
    name: 'Ilam (Kanyam)',
    category: 'nature',
    region: 'Ilam',
    province: 'Koshi',
    description: 'Rolling hills of tea gardens. A perfect getaway for nature lovers and tea enthusiasts.',
    imageUrl: 'https://images.unsplash.com/photo-1623062633718-d78b27346123?q=80&w=1000',
    bestTime: 'Feb-May, Sep-Dec',
    mediums: ['Bus', 'Flight'],
    priceRange: 'From $25/day',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'manaslu-trek',
    name: 'Manaslu Circuit',
    category: 'trekking',
    region: 'Gorkha',
    province: 'Gandaki',
    description: 'A less crowded alternative to the Annapurna Circuit. Remote, culturally rich, and physically demanding.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    difficulty: 'Hard',
    altitude: '5,106m',
    bestTime: 'Mar-May, Oct-Dec',
    mediums: ['Bus', 'Jeep', 'Trek'],
    priceRange: 'From $800',
    budgetLevel: 'Premium',
    rating: 4.9
  },
  {
    id: 'kalinchowk-snow',
    name: 'Kalinchowk Bhagwati',
    category: 'nature',
    region: 'Dolakha',
    province: 'Bagmati',
    description: 'Easy getaway from Kathmandu. Famous for winter snow, temple, and panoramic views.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    altitude: '3,842m',
    bestTime: 'Nov-Mar (Snow), Sep-Oct',
    mediums: ['Bus', 'Jeep'],
    priceRange: 'From $50',
    budgetLevel: 'Budget',
    rating: 4.7
  },
  {
    id: 'bhedetar-hill',
    name: 'Bhedetar (Dharan)',
    category: 'hill-station',
    region: 'Dhankuta',
    province: 'Koshi',
    description: 'The "Queen of Hills" in Eastern Nepal. Always cool, even when the plains are scorching.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'From $20/day',
    budgetLevel: 'Budget',
    rating: 4.6
  },
  {
    id: 'khaptad-park',
    name: 'Khaptad National Park',
    category: 'nature',
    region: 'Bajhang/Doti',
    province: 'Sudurpashchim',
    description: 'A paradise for trekkers and nature seekers. Rolling green meadows and peaceful spiritual sites.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    altitude: '3,000m',
    bestTime: 'Mar-May, Oct-Nov',
    mediums: ['Bus', 'Trek'],
    priceRange: 'From $300',
    budgetLevel: 'Mid-range',
    rating: 4.8
  },
  // --- NEW DESTINATIONS ---
  {
    id: 'gokyo-lakes',
    name: 'Gokyo Lakes',
    category: 'trekking',
    region: 'Solukhumbu',
    province: 'Koshi',
    description: 'Six spectacular glacial lakes in the Everest region. Famous for the Gokyo Ri viewpoint.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    difficulty: 'Hard',
    altitude: '4,700m',
    bestTime: 'Mar-May, Oct-Dec',
    mediums: ['Flight', 'Trek'],
    priceRange: 'From $1,000',
    budgetLevel: 'Premium',
    rating: 4.9
  },
  {
    id: 'langtang-valley',
    name: 'Langtang Valley',
    category: 'trekking',
    region: 'Rasuwa',
    province: 'Bagmati',
    description: 'The "Valley of Glaciers" closest to Kathmandu. Rebuilding strong after the 2015 earthquake.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    difficulty: 'Moderate',
    altitude: '3,870m',
    bestTime: 'Mar-May, Oct-Nov',
    mediums: ['Bus', 'Trek'],
    priceRange: 'From $400',
    budgetLevel: 'Mid-range',
    rating: 4.8
  },
  {
    id: 'sarangkot',
    name: 'Sarangkot',
    category: 'adventure',
    region: 'Kaski',
    province: 'Gandaki',
    description: 'Famous for sunrise, sunset, and paragliding. Offers one of the best views of the Annapurna range.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus', 'Trek', 'Jeep'],
    priceRange: 'From $30',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'ghale-gaun',
    name: 'Ghalegaun',
    category: 'culture',
    region: 'Lamjung',
    province: 'Gandaki',
    description: 'A model tourism village. Experience traditional Gurung hospitality and honey hunting history.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    bestTime: 'Oct-May',
    mediums: ['Jeep', 'Bus'],
    priceRange: 'From $40',
    budgetLevel: 'Budget',
    rating: 4.7
  },
  {
    id: 'swayambhunath',
    name: 'Swayambhunath',
    category: 'pilgrimage',
    region: 'Kathmandu',
    province: 'Bagmati',
    description: 'The ancient Monkey Temple. One of the oldest religious sites in Nepal with panoramic city views.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'Entry $3',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'boudhanath',
    name: 'Boudhanath Stupa',
    category: 'heritage',
    region: 'Kathmandu',
    province: 'Bagmati',
    description: 'One of the largest spherical stupas in the world. A major center for Tibetan Buddhism.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'Entry $4',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'chandragiri',
    name: 'Chandragiri Hills',
    category: 'nature',
    region: 'Kathmandu',
    province: 'Bagmati',
    description: 'Accessible by cable car. Offers a grand view of the entire Himalayan range and Kathmandu valley.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    bestTime: 'Sep-Apr',
    mediums: ['Bus', 'Jeep'],
    priceRange: 'Cable Car $22',
    budgetLevel: 'Mid-range',
    rating: 4.7
  },
  {
    id: 'begnas-lake',
    name: 'Begnas Lake',
    category: 'nature',
    region: 'Kaski',
    province: 'Gandaki',
    description: 'A peaceful alternative to Phewa Lake. Perfect for boating, fishing, and relaxation.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'From $15',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'tsho-rolpa',
    name: 'Tsho Rolpa Lake',
    category: 'trekking',
    region: 'Dolakha',
    province: 'Bagmati',
    description: 'One of the biggest glacial lakes in Nepal. Tucked between Langtang and Everest regions.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    difficulty: 'Hard',
    altitude: '4,580m',
    bestTime: 'Mar-May, Sep-Nov',
    mediums: ['Jeep', 'Trek'],
    priceRange: 'From $300',
    budgetLevel: 'Mid-range',
    rating: 4.7
  },
  {
    id: 'dhorpatan',
    name: 'Dhorpatan Reserve',
    category: 'wildlife',
    region: 'Baglung',
    province: 'Gandaki',
    description: 'The only hunting reserve in Nepal. Known for Blue Sheep and diverse Himalayan wildlife.',
    imageUrl: 'https://images.unsplash.com/photo-1623062633718-d78b27346123?q=80&w=1000',
    bestTime: 'Mar-May, Oct-Nov',
    mediums: ['Jeep', 'Bus'],
    priceRange: 'From $100/day',
    budgetLevel: 'Mid-range',
    rating: 4.6
  },
  {
    id: 'pathivara',
    name: 'Pathivara Temple',
    category: 'pilgrimage',
    region: 'Taplejung',
    province: 'Koshi',
    description: 'Sacred temple of Goddess Pathivara. Famous for spiritual significance and sunrise views.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    altitude: '3,794m',
    bestTime: 'Mar-Jun, Sep-Dec',
    mediums: ['Flight', 'Jeep', 'Trek'],
    priceRange: 'From $200',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'shuklaphanta',
    name: 'Shuklaphanta Park',
    category: 'wildlife',
    region: 'Kanchanpur',
    province: 'Sudurpashchim',
    description: 'Vast grasslands home to Swamp Deer, tigers, and diverse bird species.',
    imageUrl: 'https://images.unsplash.com/photo-1623062633718-d78b27346123?q=80&w=1000',
    bestTime: 'Oct-Apr',
    mediums: ['Bus', 'Flight'],
    priceRange: 'From $50/day',
    budgetLevel: 'Mid-range',
    rating: 4.7
  },
  {
    id: 'namobuddha',
    name: 'Namobuddha',
    category: 'pilgrimage',
    region: 'Kavre',
    province: 'Bagmati',
    description: 'A sacred Buddhist site where Buddha is believed to have sacrificed his body to a hungry tigress.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'From $10',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'panauti',
    name: 'Panauti',
    category: 'heritage',
    region: 'Kavre',
    province: 'Bagmati',
    description: 'One of the oldest towns in Nepal. Famous for Newari festivals and historic temples.',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e28?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'From $15',
    budgetLevel: 'Budget',
    rating: 4.6
  },
  {
    id: 'siddha-gufa',
    name: 'Siddha Gufa',
    category: 'adventure',
    region: 'Tanahun',
    province: 'Gandaki',
    description: 'The largest cave in Nepal. Offers a unique subterranean adventure.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    bestTime: 'Oct-May',
    mediums: ['Bus', 'Trek'],
    priceRange: 'From $10',
    budgetLevel: 'Budget',
    rating: 4.5
  },
  {
    id: 'dakshinkali',
    name: 'Dakshinkali Temple',
    category: 'pilgrimage',
    region: 'Kathmandu',
    province: 'Bagmati',
    description: 'A powerful temple of Goddess Kali located in a forest clearing.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'From $5',
    budgetLevel: 'Budget',
    rating: 4.7
  },
  {
    id: 'swargadwari',
    name: 'Swargadwari',
    category: 'pilgrimage',
    region: 'Pyuthan',
    province: 'Lumbini',
    description: 'The "Gateway to Heaven". A holy site associated with the Pandavas.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    bestTime: 'Oct-May',
    mediums: ['Bus', 'Jeep'],
    priceRange: 'From $40',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'haleshi-mahadev',
    name: 'Haleshi Mahadev',
    category: 'pilgrimage',
    region: 'Khotang',
    province: 'Koshi',
    description: 'The "Pashupatinath of East". Famous for its sacred cave temples.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus', 'Jeep'],
    priceRange: 'From $80',
    budgetLevel: 'Budget',
    rating: 4.8
  },
  {
    id: 'supa-deurali',
    name: 'Supa Deurali',
    category: 'pilgrimage',
    region: 'Arghakhanchi',
    province: 'Lumbini',
    description: 'A famous temple on a scenic hill pass. Known for fulfilling wishes.',
    imageUrl: 'https://images.unsplash.com/photo-1506191652687-c78912bb2839?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus', 'Jeep'],
    priceRange: 'From $20',
    budgetLevel: 'Budget',
    rating: 4.7
  },
  {
    id: 'khaptad-meadows',
    name: 'Khaptad Meadows',
    category: 'nature',
    region: 'Doti',
    province: 'Sudurpashchim',
    description: 'Endless rolling green hills and spiritual peacefulness in Far-West Nepal.',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=1000',
    altitude: '3,000m',
    bestTime: 'Apr-Jun, Sep-Nov',
    mediums: ['Bus', 'Trek'],
    priceRange: 'From $150',
    budgetLevel: 'Budget',
    rating: 4.9
  },
  {
    id: 'dolakha-bhimsen',
    name: 'Dolakha Bhimsen',
    category: 'pilgrimage',
    region: 'Dolakha',
    province: 'Bagmati',
    description: 'Historic temple of Bhimsen, the deity of traders and strength.',
    imageUrl: 'https://images.unsplash.com/photo-158223940be64-67d71644788c?q=80&w=1000',
    bestTime: 'All Year',
    mediums: ['Bus'],
    priceRange: 'From $10',
    budgetLevel: 'Budget',
    rating: 4.8
  }
];

export const FESTIVALS: Festival[] = [
  { name: 'Dashain', description: 'Celebrating the victory of good over evil.', month: 'Oct', icon: '🪁' },
  { name: 'Tihar', description: 'Festival of lights and the bond of siblings.', month: 'Nov', icon: '🕯️' },
  { name: 'Holi', description: 'The vibrant festival of colors.', month: 'Mar', icon: '🎨' }
];

export const TRAVEL_TIPS = [
  { 
    title: 'Altitude Safety', 
    content: 'AMS is real. Ascend no more than 500m per day once above 3,000m. Drink plenty of water.', 
    icon: '🏔️' 
  },
  { 
    title: 'Cash & ATMs', 
    content: 'ATMs are rare outside cities. Always carry enough NPR cash for your entire trek duration.', 
    icon: '💵' 
  },
  { 
    title: 'Water Safety', 
    content: 'Tap water is unsafe. Use purification tablets or UV filters to avoid plastic waste.', 
    icon: '💧' 
  },
  { 
    title: 'Local Etiquette', 
    content: 'Always walk clockwise around shrines. Remove shoes before entering homes and temples.', 
    icon: '🙏' 
  }
];
